[package]
name = "binod"
version = "0.1.1"
authors = ["Devdutt Shenoi <devdutt@outlook.in>"]
edition = "2018"
description = "The definitive BINOD, but in rust"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/de-sh/binod/"
keywords = ["Binod"]

[dependencies]
